from pathlib import Path

import mlx.core as mx
import numpy as np
import pytest


_GOLDEN_TOLERANCES = {
    "float32": (1e-3, 1e-3),
    "bfloat16": (3e-2, None),
}


def _load_prefixed(module, converted_path: Path, prefix: str) -> None:
    weights = mx.load(str(converted_path))
    module.load_weights(
        [(name.removeprefix(prefix), value) for name, value in weights.items() if name.startswith(prefix)],
        strict=True,
    )


def _assert_error(actual: mx.array, expected: np.ndarray, *, rel_l2: float, max_abs: float | None) -> None:
    actual_array = np.array(actual.astype(mx.float32))
    expected_array = expected.astype(np.float32, copy=False)
    difference = actual_array - expected_array
    relative_l2 = np.linalg.norm(difference.ravel()) / max(np.linalg.norm(expected_array.ravel()), 1e-12)
    assert relative_l2 <= rel_l2, relative_l2
    if max_abs is not None:
        assert np.max(np.abs(difference)) <= max_abs


@pytest.mark.parametrize("dtype", ("float32", "bfloat16"))
@pytest.mark.parametrize("golden", range(8), indirect=True)
def test_vision_matches_golden(
    golden,
    checkpoint_dir: Path,
    dtype: str,
) -> None:
    from smolvla_mlx.convert import convert_checkpoint
    from smolvla_mlx.vision import VisionEncoder

    # Goldens are generated by CPU PyTorch fp32. Run native MLX on its CPU
    # backend for this immutable numerical contract; GPU precision evidence is
    # recorded separately in FAILURE_vision.md rather than loosening Section 6.
    with mx.stream(mx.cpu):
        converted = convert_checkpoint(checkpoint_dir, Path(".cache/smolvla_mlx") / f"vision-{dtype}", dtype=dtype)
        vision = VisionEncoder()
        _load_prefixed(vision, converted.output_path, "vision.")
        actual = vision(
            golden.mx("preprocessed/pixel_values", getattr(mx, dtype)),
            golden.mx("preprocessed/pixel_mask", mx.bool_),
        )

    rel_l2, max_abs = _GOLDEN_TOLERANCES[dtype]
    _assert_error(actual, golden.array("vision/features"), rel_l2=rel_l2, max_abs=max_abs)
